### ISSUE TITLE
Crash on Paraguay Independence

### ISSUE THREAD

**Issue by hafizhmakmur** [SighPie/HFM#100]
I'm playing as Argentine Confederation and somewhere around 1840s event 'Paraguay Independence' came. When I choose the first option "Let them" the game immediately crash. It occurs on a previous patch. When I try to download this patch and load the most recent autosaves, the game runs more weirdly. Suddenly my ruling party become Socialists before Socialists are even founded, and the game crashes approximately one week after started. Here is the most recent autosave that I have

[autosave.zip](https://github.com/SighPie/HFM/files/1951194/autosave.zip)

**Comment by SighPie** [comment]
Save games aren't compatible when updating, I'll look into your other issue when i can

**Comment by SighPie** [comment]
Tested the Paraguay independence event, no crash occurred, should be working fine
