### ISSUE TITLE
EIC Winning the independence war

### ISSUE THREAD

**Issue by Czubaduba** [SighPie/HFM#105]
It gets annexed instantly even if it wins

**Comment by SighPie** [comment]
Is the EIC an AI?

**Comment by Czubaduba** [comment]
Yes, I don't get annexed by tagging to it for a while then when I tag back out to my country it gets annexed right away

**Comment by SighPie** [comment]
EIC isn't meant to exist as an independent AI, this is working as intended. Just don't tag switch out if you wanna play as the EIC and there won't be any issues.
