### ISSUE TITLE
Renaming decisions for Serbia and Slovenia suggestion

### ISSUE THREAD

**Issue by Uberbobo7** [SighPie/HFM#106]
Hi, 

I commented on Reddit about the renaming decisions for HFM for ex-Yugoslavia and you said I could make the necessary decisions and send them to you to consider. I'm attaching them here.

[changed.zip](https://github.com/SighPie/HFM/files/1997449/changed.zip)

I did the localisations too and I stuck to your format of keeping the text simple.

What I changed:

Added Serbian names for all provinces in Yugoslavia which are only accessible for a Serb culture nation which IS NOT also Yugoslavia. So if Yugoslavia forms it will revert the names to Croat and Slovene it would normally use in HFM to represent it being a union, rather than a Serb state. Such names were also added for Albania and Southern Macedonia. All province names used are Serbian versions of existing names, with two exceptions:

Senj is renamed to Knin which is the largest Serb majority city in the region located right on the border between the provinces of Senj and Split, possibly even a bit inside the province od Split, but since that has no Serb pops it works better if Knin is attached to the province of Senj.

Cattaro is renamed Budva, since it is larger and Cattaro has never had any real prominence after the end of A-H. It's mostly known for the fact that the Bay of Cattaro is named after it.

I also added the letter "š" where appropriate in the Rename Banat decision. The Rename N_Macedonia now uses the Serb language name for it, so "Vardarska Makedonija" instead of "Vardar Macedonia". S_Macedonia is named "Primorska Makedonija" which literally means "Coastal Macedonia". The name is analogous to the Russian state of "Primorye".

Albania is renamed "Dracki Okrug" which means Durazzo County, because it is what it was named when it was part of the Kingdom of Serbia. ( https://en.wikipedia.org/wiki/Dra%C4%8D_County ) An appropriate decision for any non-serb country to revert the names was added.

I also added the decisions for Slovenia to rename the southern part of Istria (in case it conquers it all). It can't simply use Croat or Serb names since it has its own name for Pula (Pulj).

In all cases I updated all other renaming decisions for the same provinces, so they know they have to rename back if Serbian or Slovene names have been implemented.

If you think this was an okay job I'd like to expand it to sorting out the names for Serbia proper, since North and South Serbia, as well as Bosnia currently use English names rather than domestic ones and as far as I can see increased authenticity is your goal and this would help.

Furthermore I'd like to expand the "Form Romania" decision or make a special variant for a Serbian player in which if it is taken, the vassal Romania does not take Banat. I'd like to make a similar decisions which release vassal Slovenia, Bulgaria and Hungary if you own or sphere the appropriate lands. Slovenia would be released owning Slovenia and could be expanded to own all of Istria or just the northern part (separate "expand Slovenia" decision). For Bulgaria you could choose to give them N_Macedonia, E_Macedonia and Silesia (whole or half) or not. For Hungary you could choose to give them Transylvania, Banat, Slavonia, Croatia, Fiume, Slovakia or not.

I'd also like to make a decision which allows a Serbian player to cede the Greek core province in Albania to Greece once he conquers Albania provided Greece either owns the Ionian Isles, or has a land border with it.

**Comment by clementou** [comment]
Try putting this in a pull request

**Comment by Uberbobo7** [comment]
Ok, I'll do that. I have never used Github before, so I didn't really know what "pulls" are.

**Comment by Uberbobo7** [comment]
Sorry, maybe I'm just retarded, but it doesn't allow me to open a new pull request, the button is grayed out.

**Comment by clementou** [comment]
Github is pretty complicated so don't feel bad. To do a pull request you need to open your own fork and then put the changes there. Then the pull request will stage the changes here. I did it for you this time so don't worry about it.

**Comment by Uberbobo7** [comment]
Thanks, I'll try to figure out how to use pulls if I want to suggest other changes in the future.
