### ISSUE TITLE
Broken localization for event 160027 "Qing Retreat to Formosa"

### ISSUE THREAD

**Issue by Suprcheese** [SighPie/HFM#111]
After a victorious Taiping / Heavenly Kingdom run, I noticed that the localization for the event wherein the Qing retreat to Formosa/Taiwan was broken. The event in question seems to be **id = 160027** from the **Events\Taiping.txt file**.

A screenshot illustrates the issue: https://i.imgur.com/t6aQVfk.jpg

**Comment by Suprcheese** [comment]
Further research reveals that this event seems to be almost identical to event **160026**. Curiously, event 160026 appears in both **localisation\00_HPM_events.csv** *and* **localisation\02_NNM_events.csv**

**Comment by SighPie** [comment]
Issue has been resolved in the next release, thanks
