### ISSUE TITLE
Hungarian Revolution doesn't give cb to Austrian player

### ISSUE THREAD

**Issue by clementou** [SighPie/HFM#112]
Playing as Austria, I received the Hungarian Revolution event and chose the option to fight Hungary. They were released and nothing happened. I only received the cbs to take my core and the cb to take Austrian cores. I ran a test with ai Austria and they received the "annex Hungary" cb. 

This was in a multiplayer game.

**Comment by SighPie** [comment]
Just wait 7 days and the war will start by itself
