### ISSUE TITLE
Remove Görz/Gorizia from Venezia and add it to Istria

### ISSUE THREAD

**Issue by ckanbak** [SighPie/HFM#113]
Hello, in the current version the province of Gorizia(id 733) is a part of Venezia region. This causes Italy to acquire it by annexing Venice, which is wrong historically as they acquired it only after WW1. It can also cause other weird things like Slovenia requiring releasing three regions to be released fully (Gorizia is a Slovenian core).

I suggest that it should be added to Istria(AUS_736) as this was the case [historically.](https://en.wikipedia.org/wiki/Austrian_Littoral)

**Comment by clementou** [comment]
wait it is in istria

**Comment by ckanbak** [comment]
Sorry, checked definitions.csv again and realized I had written the id wrong. It was supposed to be 733 not 736. 736 is Trieste, which is in Istria.

**Comment by clementou** [comment]
Udine is 733, Gorizia is 737, and Trieste is is 736. Udine was part of the Kingdom of Lombardy-Venetia and then the Kingdom of Italy, and Gorizia and Trieste were in the Austrian Littoral. Udine is in the Venezia state, and Gorizia and Trieste are in the Istria region. This is all in 1.27I
