### ISSUE TITLE
Makran Kalat Sindh and Kashmir stays british subjects even though the east india co. wins the revolt

### ISSUE THREAD

**Issue by DrVikyll** [SighPie/HFM#123]
Using the latest patch i found a bug where Makran Kalat Sindh and Kashmir stays british subjects and spherelings even though the east india company wins the revolt 
 Its just a few more wars but still a pretty big annoyance please HFM guy fix it soon (or if you have more played nations bugged then focus on them of course
![skjermbilde 66](https://user-images.githubusercontent.com/40180317/41250048-180cbfb8-6db6-11e8-8c36-60b8c941c48c.png)
)

**Comment by SighPie** [comment]
Issue should be fixed
