### ISSUE TITLE
Danish Strait On Conquest

### ISSUE THREAD

**Issue by Exerosp** [SighPie/HFM#124]
I conquer denmark, the province modifier disappears but the resource stays, how come other countries get events/decisions to force "me" to end the sound toll?
And if the decision is not taken or I refuse it, russia starts spamming me with the event in 1870~

**Comment by SighPie** [comment]
The modifier is just meant to help Denmark, the RGO itself represents the toll. The event has been changed to make all countries affected by the Sound Toll declare war on you, it'll probably stop the event spam.
