### ISSUE TITLE
Processing flag crash

### ISSUE THREAD

**Issue by aleindra** [SighPie/HFM#126]
the 1st launch of the game will always crash the game at 'processing flags' then the 2nd try will be launching properly but some flag are not properly alligned. if i delete the flag cache files then the cycle will continue ( the 1st and 2nd launch thingy ) 
here are some screenshot of it 
![20180621184426_1](https://user-images.githubusercontent.com/40483091/41759064-a0fef1f2-7616-11e8-888c-e466953f7f40.jpg)
![20180621184433_1](https://user-images.githubusercontent.com/40483091/41759066-a132d850-7616-11e8-985d-786d2644dc15.jpg)
![20180621184436_1](https://user-images.githubusercontent.com/40483091/41759067-a16931e8-7616-11e8-8cbe-0fe3ad18c648.jpg)
![20180621184439_1](https://user-images.githubusercontent.com/40483091/41759068-a19c57e4-7616-11e8-9fe1-f74483d330be.jpg)
and the 2 files that in the cache files
[flagfiles.txt](https://github.com/SighPie/HFM/files/2126405/flagfiles.txt)
[flagfiles_communist.txt](https://github.com/SighPie/HFM/files/2126406/flagfiles_communist.txt)

**Comment by SighPie** [comment]
You did not install the mod properly. See this guide https://youtu.be/-Gzc9GcJqXM
