### ISSUE TITLE
You can get military aid by a great power you are at war with

### ISSUE THREAD

**Issue by ghost** [SighPie/HFM#131]
I can get military aid from the country you are at war with.

**Comment by SighPie** [comment]
If possible could you provide a savefile

**Comment by SighPie** [comment]
Sorry accidently closed the issue

**Comment by ghost** [comment]
Here you can see it https://youtu.be/H0E-i8lCJeE .

**Comment by SighPie** [comment]
Issue has been fixed, apparently for some reason the Become Independent CB previously did not change your overlord's diplomatic influence on you, which caused the issue.
