### ISSUE TITLE
When you become Reserva Moskita You lose most technology and industry is dismantled.

### ISSUE THREAD

**Issue by ghost** [SighPie/HFM#132]
Why? This is such a shitty thing losing everything you worked for only because of and event you have no influence on. I was even stronger than Nicaragua and more developed and more population, I should be strong enough to say no to it!

**Comment by SighPie** [comment]
Issue itself has been resolved, but the Mosquito Kingdom itself is being changed in 1.28 to become a lot weaker than it is now.
