### ISSUE TITLE
No workers in RGO in Lamia, Greece

### ISSUE THREAD

**Issue by amyntasv** [SighPie/HFM#136]
Never seen this before with hfm.  The workforce is 90% farmers but there's no production of cotton -- nobody's working in the RGO.

Encouraging farmers briefly makes some work in the RGO and then they disappear immediately.

How do I fix this?

I don't recall noticing it in 1.27d, only in 1.27i.

**Comment by SighPie** [comment]
Issue caused by Artisan wool, issue resolved in next update
