### ISSUE TITLE
The Cisplatine Question

### ISSUE THREAD

**Issue by AFP595** [SighPie/HFM#34]
A decision for a Brazil/UPB. Can be passed if they own Uruguay, have Nationalism & Imperialism and a Jingoistic party in power; adds cores in the Uruguay state and renames it to Cisplatine.

**Comment by Shayco122** [comment]
I'll look into it.

**Comment by clementou** [comment]
This should probably be added with others to a South America Rework Milestone

**Comment by AFP595** [comment]
Yeah. 19th-century South America, with its wars and initially somewhat undefined borders, could be a great source of alt-history scenarios. Also, is anyone else able to add labels to issues? I can't, for some reason...

**Comment by Shayco122** [comment]
Ok, I just added it. You can see it at "pull request" let me know what you think.

**Comment by AFP595** [comment]
Well, actually, I thought a decision would make more sense here... let me post here the suggestion I sent once to Sighpie.

**Title:** "The Cisplatine Reclaimed"
**Potential:** Be Brazil or Portugal-Brazil.
**Condition to pass:** Be GP, at peace, have Nationalism & Imperialism, own all provinces in the Uruguay state.
**Effect:** Gain cores in all provinces with Uruguayan cores, rename Uruguay state to Cisplatine.
**Description:** "With our control over the Cisplatina confirmed, we can finally incorporate it properly into our administration. Long live the $COUNTRY$!"

**Comment by SighPie** [comment]
There's already a irredentist decision for Uruguay in the mod

**Comment by AFP595** [comment]
Wait, really? Could you point me out where can I find it?

**Comment by SighPie** [comment]
Decisions/Irredentism/provincia_cisplatina
