### ISSUE TITLE
Flags for SBA (Buenos Aires)

### ISSUE THREAD

**Issue by ghost** [SighPie/HFM#51]
I know this isn`t really important but I took the time to make alternative flags for Buenos Aires just in case.

**SBA_fascist.tga**
![fascista](https://user-images.githubusercontent.com/26846764/35503269-69b53572-04be-11e8-975a-de4ce6af80a1.png)
**SBA_monarchy.tga**
![monarquista](https://user-images.githubusercontent.com/26846764/35503271-69d8de3c-04be-11e8-91a4-4f523bd9281c.png)
**SBA_communist.tga**
![comunista](https://user-images.githubusercontent.com/26846764/35503272-69f94b54-04be-11e8-96db-395600d92ad8.png)

.tga files
https://drive.google.com/open?id=1EDoX_OxUG0-X_9X_a4U33R_Ql54qLmxC

**Comment by SighPie** [comment]
Added with thanks.
