### ISSUE TITLE
Mittelafrika

### ISSUE THREAD

**Issue by Tehfebeb** [SighPie/HFM#54]
Hello

There are alot of issues with the current Mittelafrika

first of all, the CGO congo never got cores, so its impossible to get. Dont know why they didnt in my game, but i had to give CGO a core somewhere in africa or it wouldnt work. I suspect that only france can organize Congo but im unsure

secondly, they have Mittelafrika has north german culture, so they petition to rejoin germany.

Thanks for a great mod tho

**Comment by Tehfebeb** [comment]
They also released egypt as satalite. So my dependancy had a satalite

**Comment by SighPie** [comment]
Changed the requires for forming Mittelafrika, the petition issue should also be fixed
