### ISSUE TITLE
Leipzig Congress fires over and over

### ISSUE THREAD

**Issue by GODOG4** [SighPie/HFM#69]
After annexing the Rhineland as France, the Leipzig congress event fired, but the AI can still choose the option after selecting it and it keeps on selecting it over and over and over, causing the game to be literally unplayable since the event pauses the game every day and Austria gets 100000 infamy and explodes in hundreds of containment wars.

**Comment by GODOG4** [comment]
Also the way the event works currently is a bit odd even if Austria could only take it once. They only inherent the german minor states if they are in their sphere instead of getting a cultural union automatically like the Gutter Crown. Since NGF was way stronger than AUS in my game (they lost pretty much everything but Bohemia) there still were a shit load of little german minor states. The event text also implies the German Confederation is formed but instead the GCF only replaces cores on germany proper, none on Austrian land, and Austria is the only one who inherits.

The event should be completely redone so instead it prompts a cultural union for the GCF and all the minor german states. The GCF should get cores on most of the austrian land it gets too.

**Comment by SighPie** [comment]
Issues with the event have been fixed for the next release
