### ISSUE TITLE
UTF-8 vs ISO8859-15 Encoding Issues

### ISSUE THREAD

**Issue by ozyhuboi** [SighPie/HFM#80]
Vic 2 uses the older ISO8859-15 encoding scheme, as opposed to the modern UTF-8. It's imperative to make sure all files are encoded properly in the older scheme or you get weird name display issues for special characters. 
In Notepad++: 
1. Go to "Encoding" tab at the top
2. Select "Convert to ANSI" from the dropdown
3. Then go back to "Encoding", from "Character sets", go down to "Western European"
4. Select the older scheme. 

I've noticed this issue present in several files. Please keep this in mind in the future when displaying names and such. Should go without saying that you should check the file for other changes and test the display in game.

**Comment by SighPie** [comment]
I know
