### ISSUE TITLE
What countries have the most flavor?

### ISSUE THREAD

**Issue by ghost** [SighPie/HFM#87]
Since this mod doesn't have a forum, asking here.

**Comment by Wolfenswan** [comment]
There's a dedicated thread in the pdx-forums:
https://forum.paradoxplaza.com/forum/index.php?threads/submod-hpm-historical-flavour-mod.1028707/

The /r/paradoxplaza & /r/victoria2 subreddits are also places to post questions.

As to your question, there's no definite answer and it's hard to define what 'flavor' exactly is. Almost all large and mid-sized nations have seen rework in HPM & HFM, France especially in HFM. I suggest gauging the decision & event files to get an idea of how much 'stuff' there is for each nation.
