### ISSUE TITLE
Colonial Crisis Weirdness

### ISSUE THREAD

**Issue by LemonyNelson** [SighPie/HFM#98]
You know that small southern province of Somalia that is uncolonized at the beginning of the game but is still a part of the state? Well, some spooky stuff happened there.

When the Dark Continent fired France and I (UK) got into a colonial competition over that small uncolonized bit. That competition (apparently) ended when I got an event that ceded all of the Horn of Africa over to me. That was that for a decade or so.

Then in the early 1900s a colonial crisis pops over this territory, even though it is no longer uncolonized and is my land now. Such phantom crises should not occur.

**Comment by Teitali** [comment]
That happened to me too. I was playing a game with Italy. Germany and I were doing a colonial competition to control the Horn of Africa, but everything went to the UK so randomly. Years later a crisis broke out between me and Germany for the territory that had been annexed by the United Kingdom

**Comment by LemonyNelson** [comment]
The Colonial Railroading event that pops at the beginning of the game could be modified with an option to disable some events ceding uncolonized territory.

**Comment by SighPie** [comment]
Issue should be resolved
